name: CI

# controls when action will run
on:
  # triggers workflow on push events
  push:
  # allows workflow to be triggered manually from Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [octave]
        os: [macos-latest, ubuntu-latest]
        include:
        - platform: matlab
          os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Octave (Linux)
      if: matrix.platform == 'octave' && startsWith(matrix.os, 'ubuntu')
      uses: MATPOWER/action-install-octave-linux@v1

    - name: Install Octave (macOS)
      if: matrix.platform == 'octave' && startsWith(matrix.os, 'macos')
      uses: MATPOWER/action-install-octave-macos@v1

    - name: Install MATLAB
      if: matrix.platform == 'matlab'
      uses: matlab-actions/setup-matlab@v1

    - name: Configure MATLAB
      if: matrix.platform == 'matlab'
      uses: MATPOWER/action-configure-matlab@v1
      with:
        os: ${{ matrix.os }}

    - name: ${{ env.ML_NAME }} ${{ env.ML_VER }} Installed
      run: $ML_CMD ver

    - name: Install MP-Test, Set MPTEST_PATH
      run: |
        git clone --depth=1 https://github.com/MATPOWER/mptest.git $HOME/mptest
        echo "MPTEST_PATH=$HOME/mptest/lib:$HOME/mptest/lib/t" >> $GITHUB_ENV

    - name: Install WY-Wind-Model
      run: echo "TEST_PATH=${GITHUB_WORKSPACE}/lib:${GITHUB_WORKSPACE}/lib/t:${MPTEST_PATH}" >> $GITHUB_ENV

    - name: Test WY-Wind-Model
      run: env $ML_PATHVAR=$TEST_PATH $ML_CMD "test_wy_wind(0,1)"
